package cli

import (
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"github.com/ALIRAZA47/ratline-cli/internal/buildinfo"
	"github.com/ALIRAZA47/ratline-cli/internal/rlerr"
)

// The machine-readable description of everything ratline can do.
//
// This exists for callers that are not people: an agent, a script, a generator. The
// alternative is parsing --help, which means guessing — and a tool that runs as root on
// somebody's server is the worst possible place to guess a flag name. An agent that reads
// this cannot invent `--force-yes` or decide that `db create` takes `--user` when it takes
// `--owner`, because the answer is in front of it.
//
// Generated by walking the cobra tree rather than written down, for the same reason the
// interactive menu is: a hand-maintained copy describes the tool somebody remembered,
// which is not the tool that is installed. Everything here comes from the same flagset the
// command parses, so it is accurate by construction or not at all.

// SchemaFlag is one flag as a caller needs to understand it.
type SchemaFlag struct {
	Name       string `json:"name"`
	Short      string `json:"short,omitempty"`
	Type       string `json:"type"`
	Default    string `json:"default,omitempty"`
	Usage      string `json:"usage"`
	Required   bool   `json:"required"`
	Repeatable bool   `json:"repeatable,omitempty"`
}

// SchemaCommand is one command.
type SchemaCommand struct {
	Path        string          `json:"path"`
	Name        string          `json:"name"`
	Summary     string          `json:"summary"`
	Description string          `json:"description,omitempty"`
	Args        []string        `json:"args,omitempty"`
	Flags       []SchemaFlag    `json:"flags,omitempty"`
	Mutates     bool            `json:"mutates"`
	NeedsRoot   bool            `json:"needs_root"`
	Examples    []string        `json:"examples,omitempty"`
	Subcommands []SchemaCommand `json:"subcommands,omitempty"`
}

// SchemaExit is one exit code and what a caller should do about it.
type SchemaExit struct {
	Code    int    `json:"code"`
	Name    string `json:"name"`
	Meaning string `json:"meaning"`
}

// Schema is the whole contract.
type Schema struct {
	Tool     string          `json:"tool"`
	Version  string          `json:"version"`
	Envelope map[string]any  `json:"envelope"`
	Exits    []SchemaExit    `json:"exit_codes"`
	Globals  []SchemaFlag    `json:"global_flags"`
	Commands []SchemaCommand `json:"commands"`
	Notes    []string        `json:"notes"`
}

// BuildSchema walks the command tree.
func BuildSchema(root *cobra.Command) Schema {
	s := Schema{
		Tool:    "ratline",
		Version: buildinfo.Version,
		Envelope: map[string]any{
			"description": "Every command with --json writes exactly one object to stdout. " +
				"Logs go to stderr, so stdout is always parseable.",
			"success": map[string]any{"ok": true, "command": "string", "version": "string", "data": "object"},
			"failure": map[string]any{"ok": false, "command": "string", "version": "string",
				"error": map[string]any{"code": "int", "name": "string", "message": "string", "hint": "string"}},
		},
		Notes: []string{
			"Every mutating command accepts --dry-run, which writes nothing at any layer. " +
				"Run it first and read the plan.",
			"Exit codes are a contract; branch on them rather than on message text.",
			"Secrets are never accepted as flag values. --stdin, or a prompt on a terminal.",
			"Commands are safe to run twice: re-running one that has already been applied " +
				"reports what exists rather than failing.",
		},
	}
	s.Globals = append(s.Globals, globalFlagSet()...)
	s.Exits = append(s.Exits, schemaExits()...)
	for _, c := range runnableChildren(root) {
		s.Commands = append(s.Commands, describeCommand(c))
	}
	return s
}

func describeCommand(cmd *cobra.Command) SchemaCommand {
	sc := SchemaCommand{
		Path:      cmd.CommandPath(),
		Name:      cmd.Name(),
		Summary:   cmd.Short,
		Args:      positionalNames(cmd.Use),
		Mutates:   annotated(cmd, AnnoMutates),
		NeedsRoot: !annotated(cmd, AnnoAllowNonRoot),
	}
	// The first paragraph only: the rest is prose for a reader, and a caller that needs it
	// can run `ratline explain`.
	if cmd.Long != "" {
		sc.Description = strings.SplitN(strings.TrimSpace(cmd.Long), "\n\n", 2)[0]
	}
	if cmd.Example != "" {
		for _, line := range strings.Split(cmd.Example, "\n") {
			if line = strings.TrimSpace(line); line != "" && !strings.HasPrefix(line, "#") {
				sc.Examples = append(sc.Examples, line)
			}
		}
	}
	cmd.NonInheritedFlags().VisitAll(func(f *pflag.Flag) {
		if f.Hidden || f.Deprecated != "" {
			return
		}
		sc.Flags = append(sc.Flags, describeFlag(f))
	})
	sort.Slice(sc.Flags, func(i, j int) bool { return sc.Flags[i].Name < sc.Flags[j].Name })

	for _, child := range runnableChildren(cmd) {
		sc.Subcommands = append(sc.Subcommands, describeCommand(child))
	}
	return sc
}

func describeFlag(f *pflag.Flag) SchemaFlag {
	kind := f.Value.Type()
	return SchemaFlag{
		Name:       f.Name,
		Short:      f.Shorthand,
		Type:       kind,
		Default:    defaultFor(f),
		Usage:      f.Usage,
		Required:   requiredFlag(f),
		Repeatable: kind == "stringArray" || kind == "stringSlice",
	}
}

// defaultFor omits the noise defaults, so a caller can tell "unset" from "false".
func defaultFor(f *pflag.Flag) string {
	switch f.DefValue {
	case "", "false", "[]", "0":
		return ""
	}
	return f.DefValue
}

func globalFlagSet() []SchemaFlag {
	var out []SchemaFlag
	root := NewRootCommand(&Globals{})
	root.PersistentFlags().VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		out = append(out, describeFlag(f))
	})
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func schemaExits() []SchemaExit {
	codes := []rlerr.Code{
		rlerr.CodeOK, rlerr.CodeGeneric, rlerr.CodeUsage, rlerr.CodePrecondition,
		rlerr.CodeExternal, rlerr.CodeLocked, rlerr.CodeRollbackFailed,
		rlerr.CodeUnhealthy, rlerr.CodeACME, rlerr.CodeRateLimited, rlerr.CodeInputRequired,
	}
	meaning := map[rlerr.Code]string{
		rlerr.CodeOK:             "success",
		rlerr.CodeGeneric:        "an unclassified failure; read the message",
		rlerr.CodeUsage:          "the arguments were wrong; fix them rather than retrying",
		rlerr.CodePrecondition:   "the system is not in a state where this can run; the hint names what to change",
		rlerr.CodeExternal:       "an external command failed; its output is in the error",
		rlerr.CodeLocked:         "another ratline invocation holds the lock; retry shortly",
		rlerr.CodeRollbackFailed: "the operation failed and so did its undo; the server needs a human",
		rlerr.CodeUnhealthy:      "it started but never answered; the previous version is still serving",
		rlerr.CodeACME:           "the certificate challenge failed; do not retry blindly, it costs a rate limit",
		rlerr.CodeRateLimited:    "the CA's limit would be exceeded; wait rather than retrying",
		rlerr.CodeInputRequired:  "input was needed and there was no terminal; supply it as a flag or on stdin",
	}
	out := make([]SchemaExit, 0, len(codes))
	for _, c := range codes {
		out = append(out, SchemaExit{Code: int(c), Name: c.Name(), Meaning: meaning[c]})
	}
	return out
}

func newSchemaCommand(g *Globals) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "schema",
		Short: "Print the whole command surface as JSON, for tools and agents",
		Args:  cobra.NoArgs,
		Long: "Every command, every flag with its type and whether it is required, the exit\n" +
			"codes and the shape of the --json envelope.\n\n" +
			"This is for callers that are not people. Parsing --help means guessing, and a\n" +
			"tool that runs as root is the worst place to guess a flag name — so the contract\n" +
			"is published rather than inferred.\n\n" +
			"Generated by walking the command tree, so it describes the binary you are\n" +
			"holding rather than the one somebody documented.",
		Example: "  ratline schema | jq '.commands[] | select(.name==\"site\")'\n" +
			"  ratline schema | jq -r '.. | objects | select(.required==true) | .name'",
		RunE: func(cmd *cobra.Command, _ []string) error {
			schema := BuildSchema(NewRootCommand(g))
			// Always JSON: a schema is the one thing with no human rendering worth having,
			// and a caller should not have to remember --json to get it.
			return g.writeJSON(schema)
		},
	}
	return NonRoot(cmd)
}
