// Package rl is the panel's only way of doing anything: it builds argv slices and
// runs the ratline binary.
//
// Nothing else in the panel touches the system. That is the whole design. ratline
// already stages every mutation, validates it with the real tool, commits it
// atomically and unwinds a rollback stack when a step fails — and it takes the global
// lock, writes the audit record and refuses the contradictions. A panel that
// reimplemented any of that would be a second, worse ratline that drifts from the
// first, so this one is a caller.
//
// Two consequences worth stating, because they are load-bearing:
//
//   - The command surface is read from `ratline schema` at runtime, not written down
//     here. The schema is generated by walking the real cobra tree, so it describes the
//     binary that is installed. A hand-kept copy would describe the binary somebody
//     remembered, and the panel would offer a flag that no longer exists or miss one
//     that was added. What *is* written down here is policy — who may run what, what
//     needs typing a name to confirm, what runs as a job — because that is a judgement
//     and not a fact about the binary.
//
//   - An argv slice is built element by element from typed values. No string is ever
//     split into a command line, there is no shell anywhere, and a value that fails
//     validation here never reaches execve. ratline validates it again on the other
//     side; this is the first of the two, not the only one.
package rl

import (
	"context"
	"encoding/json"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/ALIRAZA47/ratline-cli/internal/rlerr"
)

// Schema mirrors what `ratline schema` prints. It is deliberately a separate
// declaration from internal/cli's: the panel is a consumer of a published contract,
// and reading it through the producer's own structs would hide the day the contract
// changed shape. A test asserts the two still agree.
type Schema struct {
	Tool     string          `json:"tool"`
	Version  string          `json:"version"`
	Exits    []SchemaExit    `json:"exit_codes"`
	Globals  []SchemaFlag    `json:"global_flags"`
	Commands []SchemaCommand `json:"commands"`
	Notes    []string        `json:"notes"`
}

// SchemaExit is one exit code and what a caller should do about it.
type SchemaExit struct {
	Code    int    `json:"code"`
	Name    string `json:"name"`
	Meaning string `json:"meaning"`
}

// SchemaFlag is one flag as the binary declares it.
type SchemaFlag struct {
	Name       string `json:"name"`
	Short      string `json:"short,omitempty"`
	Type       string `json:"type"`
	Default    string `json:"default,omitempty"`
	Usage      string `json:"usage"`
	Required   bool   `json:"required"`
	Repeatable bool   `json:"repeatable,omitempty"`
}

// SchemaCommand is one command and its children.
type SchemaCommand struct {
	Path        string          `json:"path"`
	Name        string          `json:"name"`
	Summary     string          `json:"summary"`
	Description string          `json:"description,omitempty"`
	Args        []string        `json:"args,omitempty"`
	Flags       []SchemaFlag    `json:"flags,omitempty"`
	Mutates     bool            `json:"mutates"`
	NeedsRoot   bool            `json:"needs_root"`
	Examples    []string        `json:"examples,omitempty"`
	Subcommands []SchemaCommand `json:"subcommands,omitempty"`
}

// Leaf reports whether the command runs rather than grouping others.
func (c *SchemaCommand) Leaf() bool { return len(c.Subcommands) == 0 }

// Verb is the command path with the tool name removed: ["site", "deploy"].
func (c *SchemaCommand) Verb() string {
	return strings.TrimSpace(strings.TrimPrefix(c.Path, "ratline "))
}

// Catalogue is the schema flattened to its leaves, indexed by verb.
type Catalogue struct {
	Version string
	Leaves  map[string]*SchemaCommand
	Order   []string
}

// Flag finds one flag on one command.
func (c *Catalogue) Flag(verb, name string) (SchemaFlag, bool) {
	cmd, ok := c.Leaves[verb]
	if !ok {
		return SchemaFlag{}, false
	}
	for _, f := range cmd.Flags {
		if f.Name == name {
			return f, true
		}
	}
	return SchemaFlag{}, false
}

// flatten walks the tree, collecting the commands that actually run.
//
// Groups are skipped as actions: `ratline site` on its own does nothing but print
// help, so offering it would give the panel a button that cannot fail and cannot do
// anything either. But their *flags* are carried down, and that is not a nicety.
//
// `--engine` is declared once, as a persistent flag on `db`, and applies to every
// verb beneath it. The schema reports each command's own flags — globals are listed
// separately rather than repeated ninety times — so a group's persistent flags appear
// on the group and nowhere else. Dropping them here meant the panel's `db create`
// form had no engine field at all, and every database action it ran went to MongoDB
// with no way to say otherwise. A third of the database feature was unreachable.
func flatten(cmds []SchemaCommand, inherited []SchemaFlag, into *Catalogue) {
	for i := range cmds {
		c := &cmds[i]
		if c.Leaf() {
			verb := c.Verb()
			if verb == "" {
				continue
			}
			c.Flags = mergeFlags(c.Flags, inherited)
			into.Leaves[verb] = c
			into.Order = append(into.Order, verb)
			continue
		}
		flatten(c.Subcommands, mergeFlags(inherited, c.Flags), into)
	}
}

// mergeFlags adds the ones a command did not declare itself, keeping name order.
//
// A leaf that redeclares an inherited name wins: it is the flagset the command
// actually parses, and its help text is the one describing what it does there.
func mergeFlags(own, inherited []SchemaFlag) []SchemaFlag {
	if len(inherited) == 0 {
		return own
	}
	have := make(map[string]bool, len(own))
	for _, f := range own {
		have[f.Name] = true
	}
	out := make([]SchemaFlag, 0, len(own)+len(inherited))
	out = append(out, own...)
	for _, f := range inherited {
		if !have[f.Name] {
			out = append(out, f)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// ParseSchema reads what the binary printed.
func ParseSchema(raw []byte) (*Catalogue, error) {
	var s Schema
	if err := json.Unmarshal(raw, &s); err != nil {
		return nil, rlerr.Wrap(err, rlerr.CodeExternal, "reading the output of 'ratline schema'").
			WithHint("the installed ratline may be too old for this panel; run 'ratline version'")
	}
	if s.Tool != "ratline" || len(s.Commands) == 0 {
		return nil, rlerr.Preconditionf("'ratline schema' did not describe a ratline command tree").
			WithHint("check that panel.yaml's ratline.binary points at the ratline binary")
	}
	cat := &Catalogue{Version: s.Version, Leaves: map[string]*SchemaCommand{}}
	flatten(s.Commands, nil, cat)
	return cat, nil
}

// schemaCache holds the parsed catalogue between requests.
//
// Re-reading it per request would fork a process to answer "which flags does site add
// take", which is both slow and pointless: the answer changes when the binary
// changes. It is refreshed on a timer so that `ratline update` in another terminal is
// noticed without restarting the panel, and explicitly after the panel itself runs
// an update.
type schemaCache struct {
	mu        sync.RWMutex
	cat       *Catalogue
	loadedAt  time.Time
	ttl       time.Duration
	loadError error
}

func (c *schemaCache) get(ctx context.Context, load func(context.Context) (*Catalogue, error)) (*Catalogue, error) {
	c.mu.RLock()
	if c.cat != nil && time.Since(c.loadedAt) < c.ttl {
		defer c.mu.RUnlock()
		return c.cat, nil
	}
	c.mu.RUnlock()

	c.mu.Lock()
	defer c.mu.Unlock()
	// Another goroutine may have loaded it while this one waited.
	if c.cat != nil && time.Since(c.loadedAt) < c.ttl {
		return c.cat, nil
	}
	cat, err := load(ctx)
	if err != nil {
		// A stale catalogue beats no catalogue: the panel can still work while the
		// binary is briefly unreadable mid-upgrade.
		c.loadError = err
		if c.cat != nil {
			return c.cat, nil
		}
		return nil, err
	}
	c.cat, c.loadedAt, c.loadError = cat, time.Now(), nil
	return cat, nil
}

func (c *schemaCache) invalidate() {
	c.mu.Lock()
	c.loadedAt = time.Time{}
	c.mu.Unlock()
}
