import { Link } from 'react-router-dom';
import { CodeBlock } from '../../components/CodeBlock';
import { PageHeader } from '../../components/PageHeader';
import { Terminal } from '../../components/Terminal';
import { Callout, Facts, H2, H3 } from '../../components/ui';

/**
 * What an agent needs from a root tool is not cleverness. It is: a way to find out what
 * commands exist without guessing, structured results it can branch on, and a boundary it
 * cannot talk its way past.
 */
export function GuideAgents() {
  return (
    <article>
      <PageHeader
        eyebrow="Guide"
        title="Driving ratline from an AI agent"
        lede="A published command contract so nothing has to be guessed, and an MCP server that is read-only until you say otherwise."
      />

      <Facts
        rows={[
          ['discovery', <><code>ratline schema</code> — every command and flag as JSON</>],
          ['protocol', <><code>ratline mcp</code> — MCP over stdio</>],
          ['default', 'read-only; the mutating tools are not listed at all'],
          ['results', <>the same <Link to="/reference/json">JSON envelope</Link> the CLI produces</>],
        ]}
      />

      <div className="prose">
        <H2 id="problem">What goes wrong without this</H2>
        <p>
          An agent asked to deploy something will read <code>--help</code>, infer a flag,
          and run it as root. The failure mode is not that it refuses — it is that it
          confidently invents <code>--user</code> where the command wants{' '}
          <code>--owner</code>, or retries an ACME issuance that has already burned four of
          five attempts this hour. Both are the tool's fault for making them guessable.
        </p>

        <H2 id="schema">The contract</H2>
        <p>
          <code>ratline schema</code> prints the whole surface: every command, every flag
          with its type, default and whether it is required, the exit codes with what to do
          about each, and the shape of the envelope. It is generated by walking the command
          tree, so it describes the binary in front of you rather than a document somebody
          maintained.
        </p>
      </div>

      <CodeBlock
        lang="shell"
        prompt
        code={`ratline schema | jq '.commands[] | select(.name == "db")'

# every flag a command will refuse to run without
ratline schema | jq -r '.. | objects | select(.required == true) | .name'`}
      />

      <Terminal title="an agent reading the contract">{`$ ratline schema | jq '.. | objects | select(.path == "ratline db create")'
{
  "path": "ratline db create",
  "args": ["<name>"],
  "mutates": true,
  "flags": [
    { "name": "owner",  "type": "string", "required": true  },
    { "name": "attach", "type": "string", "required": false },
    { "name": "user",   "type": "string", "required": false }
  ]
}`}</Terminal>

      <Callout tone="note" title="It cannot drift">
        <p>
          The schema comes from the same flagset the command parses. A flag added tomorrow
          is in it tomorrow; one that is renamed cannot leave a stale entry behind. That is
          the whole reason it is generated rather than written.
        </p>
      </Callout>

      <div className="prose">
        <H2 id="mcp">The MCP server</H2>
        <p>
          <code>ratline mcp</code> speaks the Model Context Protocol on stdin and stdout, so
          an agent can call tools directly instead of shelling out and parsing prose.
        </p>
      </div>

      <CodeBlock
        lang="json"
        code={`{
  "mcpServers": {
    "ratline": {
      "command": "ssh",
      "args": ["root@server.example.com", "ratline", "mcp"]
    }
  }
}`}
      />

      <div className="prose">
        <p>Nine tools, all read-only:</p>
      </div>

      <Facts
        rows={[
          ['ratline_status', 'tenants, sites, certificates, problem count'],
          ['ratline_schema', 'the contract above, so the agent can learn the rest'],
          ['ratline_site_list / _show', 'what exists, and one site in full'],
          ['ratline_site_troubleshoot', 'the whole chain in dependency order, first fault named'],
          ['ratline_site_logs', 'recent lines, secrets redacted'],
          ['ratline_doctor', 'every check, reporting only what is wrong'],
          ['ratline_db_list', 'provisioned databases; no password is ever returned'],
          ['ratline_explain', 'the long-form documentation, by topic'],
        ]}
      />

      <div className="prose">
        <H2 id="mutations">Letting it change things</H2>
        <p>
          <code>--allow-mutations</code> adds two more: <code>ratline_site_deploy</code> and{' '}
          <code>ratline_site_restart</code>. Nothing else — no <code>site delete</code>, no{' '}
          <code>db drop</code>, no <code>user delete</code>. Those exist and an agent can
          read the schema and tell you what to run; it cannot run them itself.
        </p>
      </div>

      <CodeBlock lang="shell" prompt code={`ratline mcp --allow-mutations`} />

      <Callout tone="warn" title="Absent, not refused">
        <p>
          Without the flag the mutating tools are not in <code>tools/list</code> at all. A
          tool an agent can see is a tool it will eventually try, and a refusal it can retry
          is an invitation to find a way around it. If it calls one by name anyway, the
          error says what it is and which flag would enable it — so the agent tells you,
          rather than looping.
        </p>
      </Callout>

      <div className="prose">
        <H2 id="properties">What the agent can rely on</H2>
        <H3 id="p-envelope">Every result is the envelope</H3>
        <p>
          Success or failure, the tool returns{' '}
          <code>{'{ok, command, version, data}'}</code> — and on failure an{' '}
          <code>error</code> with a numeric{' '}
          <Link to="/reference/exit-codes">code</Link>, its name, and a hint naming what to
          change. An agent branches on the code rather than on message text.
        </p>
        <H3 id="p-dryrun">Everything can be rehearsed</H3>
        <p>
          Every mutating command takes <code>--dry-run</code>, which writes nothing at any
          layer — not a state row, not a port reservation, not a file. The deploy tool
          exposes it as <code>dry_run</code>, and asking an agent to run that first and show
          you the plan costs nothing.
        </p>
        <H3 id="p-idempotent">Retrying is safe</H3>
        <p>
          Commands are idempotent: re-running one that has already been applied reports what
          exists rather than failing or duplicating. A deploy step that fails leaves the
          previous version serving, so a confused agent retrying a deploy cannot take a site
          down.
        </p>
        <H3 id="p-audit">Every call is on the record</H3>
        <p>
          Each tool call is written to the audit log with the arguments it was given, so
          "what did the agent do last Tuesday" is answerable. Secrets are redacted there as
          everywhere else.
        </p>

        <H2 id="limits">What this does not do</H2>
        <p>
          It is a boundary, not a sandbox. An agent with the mutating tools can deploy code
          to a site, and deploying code is arbitrary code execution as that tenant — the
          same as handing someone a deploy key. The gate limits which ratline commands run,
          not what the deployed application does.
        </p>
        <p>
          Run it over SSH with a key that reaches one server, keep{' '}
          <code>--allow-mutations</code> off for anything exploratory, and read{' '}
          <Link to="/concepts/security">the security model</Link> for where the isolation
          stops.
        </p>
      </div>
    </article>
  );
}
