package sshkey

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/ALIRAZA47/ratline-cli/internal/rlerr"
	"github.com/ALIRAZA47/ratline-cli/internal/state"
	"github.com/ALIRAZA47/ratline-cli/internal/system"
)

// SSHDConfigPath is the main config ratline may add an Include line to.
const SSHDConfigPath = "/etc/ssh/sshd_config"

// StrictSite is one site to confine with a chroot under strict isolation.
type StrictSite struct {
	Owner  string
	Domain string
	Dir    string
}

// RenderDropIn produces /etc/ssh/sshd_config.d/60-ratline.conf.
//
// ratline owns exactly this file and nothing else under /etc/ssh. It never
// touches PermitRootLogin, PasswordAuthentication, AllowUsers or Port, because
// changing any of those on a remote server can end the operator's own session.
func RenderDropIn(users []*state.User, revokedKeysPath string) []byte {
	return renderDropIn(users, revokedKeysPath, nil)
}

// RenderDropInStrict adds ChrootDirectory blocks for strict isolation.
//
// This is the optional stronger form of site scope. sshd's ChrootDirectory
// requires every component of the path to be owned by root and not writable by
// group or other, which a tenant's own home is not — so the chroot target is a
// root-owned directory with the site bind-mounted inside it, and the mount is
// what `site add` sets up when strict isolation is on.
//
// It is off by default because a misconfigured chroot produces a login that fails
// with nothing useful in the log, which is a support ticket generator. Where real
// isolation is wanted, one user per site is simpler and kernel-enforced.
func RenderDropInStrict(users []*state.User, revokedKeysPath string, strict []StrictSite) []byte {
	return renderDropIn(users, revokedKeysPath, strict)
}

func renderDropIn(users []*state.User, revokedKeysPath string, strict []StrictSite) []byte {
	var b strings.Builder
	b.WriteString(system.ManagedHeader + "\n")
	b.WriteString("# Generated by ratline. Edit ratline's configuration instead of this file:\n")
	b.WriteString("# it is regenerated whenever users or keys change.\n")
	b.WriteString("#\n")
	b.WriteString("# ratline deliberately does not set PermitRootLogin, PasswordAuthentication,\n")
	b.WriteString("# AllowUsers or Port here. Those belong to you.\n\n")

	if revokedKeysPath != "" {
		b.WriteString("# A backstop: sshd refuses these keys regardless of any authorized_keys file.\n")
		b.WriteString("RevokedKeys " + revokedKeysPath + "\n\n")
	}

	var sftpOnly []string
	for _, u := range users {
		if u.SFTPOnly {
			sftpOnly = append(sftpOnly, u.Name)
		}
	}
	if len(sftpOnly) > 0 {
		b.WriteString("# SFTP-only tenants: chrooted to their home, no shell, no forwarding.\n")
		b.WriteString("# ChrootDirectory requires the home to be owned by root and not group-writable,\n")
		b.WriteString("# which is why the writable content lives in subdirectories beneath it.\n")
		b.WriteString("Match User " + strings.Join(sftpOnly, ",") + "\n")
		b.WriteString("    ForceCommand internal-sftp\n")
		b.WriteString("    ChrootDirectory %h\n")
		b.WriteString("    AllowTcpForwarding no\n")
		b.WriteString("    AllowAgentForwarding no\n")
		b.WriteString("    X11Forwarding no\n")
		b.WriteString("    PermitTunnel no\n")
		b.WriteString("    PermitTTY no\n")
	}

	if len(strict) > 0 {
		b.WriteString("\n# Strict isolation. The chroot target is root-owned with the site\n")
		b.WriteString("# bind-mounted inside it, because sshd requires every component of a\n")
		b.WriteString("# ChrootDirectory path to be root-owned and not group-writable — which a\n")
		b.WriteString("# tenant's own home directory is not.\n")
		for _, s := range strict {
			b.WriteString("Match User " + s.Owner + "\n")
			b.WriteString("    ChrootDirectory " + s.Dir + "\n")
			b.WriteString("    ForceCommand internal-sftp -d /site\n")
			b.WriteString("    AllowTcpForwarding no\n")
			b.WriteString("    AllowAgentForwarding no\n")
			b.WriteString("    X11Forwarding no\n")
			b.WriteString("    PermitTunnel no\n")
			b.WriteString("    PermitTTY no\n")
		}
	}
	return []byte(b.String())
}

// ApplyDropIn writes the drop-in and reloads sshd, rolling the change back if
// anything about it looks unsafe.
//
// The order is not negotiable, because bricking SSH on a remote VPS has no
// recovery path:
//
//  1. back up, write, then run sshd -t and restore on failure
//  2. reload rather than restart, so existing sessions survive
//  3. prove that login still works, and restore if it does not
func (m *Manager) ApplyDropIn(ctx context.Context) (err error) {
	users, err := m.State.ListUsers(ctx)
	if err != nil {
		return err
	}
	path := m.Cfg.Paths.SSHDDropIn
	desired := RenderDropIn(users, m.Cfg.SSH.RevokedKeys)

	if system.Exists(path) {
		managed, err := system.HasManagedHeader(path)
		if err != nil {
			return err
		}
		if !managed {
			return rlerr.Preconditionf("%s exists but was not created by ratline", path).
				WithHint("move it aside if you want ratline to manage it")
		}
		if existing, err := system.ReadFileLimit(path, 1<<20); err == nil && string(existing) == string(desired) {
			m.Log.Debug("the sshd drop-in is already correct", "path", path)
			return nil
		}
	}

	if _, err := system.EnsureDir(filepath.Dir(path), 0o755, system.KeepUnchanged, system.KeepUnchanged); err != nil {
		return err
	}
	if err := m.ensureIncludeLine(ctx); err != nil {
		return err
	}

	if m.DryRun {
		m.Log.Info("would write the sshd drop-in and reload sshd", "path", path)
		return nil
	}

	var backup string
	if system.Exists(path) {
		if backup, err = system.BackupFile(path, time.Now().UTC().Format("20060102T150405Z")); err != nil {
			return err
		}
	}
	restore := func() {
		if backup != "" {
			if cerr := system.CopyFile(backup, path, 0o644, 0, 0); cerr != nil {
				m.Log.Error("could not restore the sshd drop-in", "backup", backup, "err", cerr)
				return
			}
		} else {
			_ = os.Remove(path)
		}
		if _, rerr := m.Runner.Run(ctx, system.Cmd{Name: "systemctl", Args: []string{"reload", "ssh"},
			Mutates: true, OKExit: []int{1, 5}}); rerr != nil {
			m.Log.Error("could not reload sshd after restoring the previous configuration", "err", rerr)
		}
	}

	if err := system.WriteFileAtomic(path, desired, 0o644, 0, 0); err != nil {
		return err
	}
	m.Log.Info("wrote the sshd drop-in", "path", path, "sftp_only_users", countSFTPOnly(users))

	// Step 1: syntax. A drop-in that does not parse takes the whole daemon down
	// on its next start, so this runs before anything is reloaded.
	if res, terr := m.Runner.Run(ctx, system.Cmd{Name: "sshd", Args: []string{"-t"}}); terr != nil {
		restore()
		return rlerr.Wrap(terr, rlerr.CodePrecondition, "the generated sshd configuration is not valid, so it was reverted").
			WithField("sshd_output", firstLines(res)).
			WithHint("this is a ratline bug; the previous configuration is back in place and SSH is unaffected")
	}

	// Step 2: reload, never restart.
	if _, rerr := m.Runner.Run(ctx, system.Cmd{Name: "systemctl", Args: []string{"reload", "ssh"},
		Mutates: true, Label: "reload sshd"}); rerr != nil {
		// Some hosts name the unit sshd rather than ssh.
		if _, rerr2 := m.Runner.Run(ctx, system.Cmd{Name: "systemctl", Args: []string{"reload", "sshd"},
			Mutates: true, Label: "reload sshd"}); rerr2 != nil {
			restore()
			return rlerr.Wrap(rerr, rlerr.CodeExternal, "could not reload sshd, so the change was reverted")
		}
	}

	// Step 3: prove login still works.
	if m.Cfg.SSH.VerifyAfterChange {
		if verr := m.VerifyLogin(ctx, users); verr != nil {
			restore()
			return rlerr.Wrap(verr, rlerr.CodePrecondition, "the sshd change was reverted because login could not be verified")
		}
	}
	return nil
}

// ensureIncludeLine adds the Include directive when the distribution's
// sshd_config lacks it, so a drop-in is actually read.
func (m *Manager) ensureIncludeLine(ctx context.Context) error {
	if !system.Exists(SSHDConfigPath) {
		return nil
	}
	data, err := system.ReadFileLimit(SSHDConfigPath, 1<<20)
	if err != nil {
		return err
	}
	body := string(data)
	if regexp.MustCompile(`(?mi)^\s*Include\s+/etc/ssh/sshd_config\.d/`).MatchString(body) {
		return nil
	}
	if m.DryRun {
		m.Log.Info("would add an Include line to " + SSHDConfigPath)
		return nil
	}
	backup, err := system.BackupFile(SSHDConfigPath, time.Now().UTC().Format("20060102T150405Z"))
	if err != nil {
		return err
	}
	m.Log.Warn("adding an Include line to the main sshd configuration",
		"path", SSHDConfigPath, "backup", backup,
		"rollback", "cp "+backup+" "+SSHDConfigPath+" && systemctl reload ssh")

	// The Include must come first: sshd takes the first value it sees for most
	// keywords, so an Include at the end cannot override anything above it.
	updated := "# Added by ratline so that /etc/ssh/sshd_config.d/*.conf is read.\n" +
		"Include /etc/ssh/sshd_config.d/*.conf\n\n" + body
	return system.WriteFileAtomicPreserve(SSHDConfigPath, []byte(updated), 0o600)
}

// VerifyLogin proves that key-based login still works after a configuration
// change.
//
// ratline holds no private key belonging to the operator, so it cannot log in as
// them. What it can do is stronger than a bare TCP check and does not require
// installing a key of its own: ask sshd for the *effective* configuration it
// would apply to each managed account with `sshd -T -C`, and assert that public
// key authentication is on, that the authorized_keys path is the one ratline
// writes, and that no Match block excludes the account. Then confirm the daemon
// is actually answering on its port.
//
// A genuinely end-to-end authentication test would mean ratline generating and
// installing a key of its own, which is a permanent extra credential on the box
// in exchange for a marginally stronger check. That trade is not worth it, and
// SSH.md says so plainly.
func (m *Manager) VerifyLogin(ctx context.Context, users []*state.User) error {
	accounts := []string{}
	if admin := m.Cfg.Server.AdminUser; admin != "" {
		accounts = append(accounts, admin)
	}
	for _, u := range users {
		if !u.Disabled {
			accounts = append(accounts, u.Name)
		}
		if len(accounts) >= 5 {
			break // a sample is enough to catch a broken Match block
		}
	}
	if len(accounts) == 0 {
		m.Log.Debug("no accounts to verify against")
		return nil
	}

	for _, account := range accounts {
		res, err := m.Runner.Run(ctx, system.Cmd{
			Name: "sshd",
			Args: []string{"-T", "-C", "user=" + account + ",host=localhost,addr=127.0.0.1"},
		})
		if err != nil {
			return rlerr.Wrap(err, rlerr.CodePrecondition,
				"sshd could not report the effective configuration for %s", account)
		}
		effective := parseEffectiveConfig(res.Stdout)
		if v := effective["pubkeyauthentication"]; v != "" && v != "yes" {
			return rlerr.Preconditionf("public key authentication is %q for %s", v, account)
		}
		if v := effective["authorizedkeysfile"]; v != "" && !mentionsAuthorizedKeys(v) {
			return rlerr.Preconditionf("sshd would read %q for %s rather than the file ratline writes", v, account)
		}
		if forced := effective["forcecommand"]; forced != "" && !strings.Contains(forced, "internal-sftp") && !strings.Contains(forced, "ratline") {
			return rlerr.Preconditionf("a ForceCommand of %q applies to %s", forced, account)
		}
	}

	// And the daemon is really listening. A configuration that parses but a
	// process that died is still a lockout.
	port := 22
	if res, err := m.Runner.Run(ctx, system.Cmd{Name: "sshd", Args: []string{"-T"}}); err == nil {
		if p := parseEffectiveConfig(res.Stdout)["port"]; p != "" {
			if n, err := strconv.Atoi(strings.Fields(p)[0]); err == nil {
				port = n
			}
		}
	}
	if err := system.ProbeTCP(ctx, fmt.Sprintf("127.0.0.1:%d", port), 5*time.Second); err != nil {
		return rlerr.Wrap(err, rlerr.CodePrecondition, "sshd is not accepting connections on port %d", port)
	}
	m.Log.Info("login verified", "accounts", len(accounts), "port", port)
	return nil
}

// parseEffectiveConfig turns `sshd -T` output into a map. Keywords are
// case-insensitive and repeated keywords accumulate.
func parseEffectiveConfig(out string) map[string]string {
	m := map[string]string{}
	for _, line := range strings.Split(out, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		key, value, ok := strings.Cut(line, " ")
		if !ok {
			continue
		}
		key = strings.ToLower(key)
		if existing, seen := m[key]; seen {
			m[key] = existing + " " + value
			continue
		}
		m[key] = strings.TrimSpace(value)
	}
	return m
}

func mentionsAuthorizedKeys(v string) bool {
	return strings.Contains(v, "authorized_keys") || strings.Contains(v, "%h/.ssh")
}

// DetectExpirySupport reports whether this sshd understands expiry-time=, which
// arrived in OpenSSH 8.2. On an older daemon the option is a parse error that
// breaks the whole file, so it is detected rather than assumed.
func (m *Manager) DetectExpirySupport(ctx context.Context) bool {
	res, err := m.Runner.Run(ctx, system.Cmd{Name: "sshd", Args: []string{"-V"}, OKExit: []int{1, 255}})
	if res == nil {
		return false
	}
	_ = err
	out := res.Stdout + res.Stderr
	major, minor, ok := parseOpenSSHVersion(out)
	if !ok {
		m.Log.Debug("could not determine the OpenSSH version; assuming expiry-time is unsupported", "output", firstLines(res))
		return false
	}
	return major > 8 || (major == 8 && minor >= 2)
}

var opensshVersionRe = regexp.MustCompile(`OpenSSH_(\d+)\.(\d+)`)

func parseOpenSSHVersion(s string) (int, int, bool) {
	m := opensshVersionRe.FindStringSubmatch(s)
	if m == nil {
		return 0, 0, false
	}
	major, err1 := strconv.Atoi(m[1])
	minor, err2 := strconv.Atoi(m[2])
	return major, minor, err1 == nil && err2 == nil
}

func countSFTPOnly(users []*state.User) int {
	n := 0
	for _, u := range users {
		if u.SFTPOnly {
			n++
		}
	}
	return n
}

func firstLines(res *system.Result) string {
	if res == nil {
		return ""
	}
	out := res.Stderr
	if strings.TrimSpace(out) == "" {
		out = res.Stdout
	}
	lines := strings.Split(strings.TrimSpace(out), "\n")
	if len(lines) > 3 {
		lines = lines[:3]
	}
	return strings.Join(lines, "; ")
}
