#!/usr/bin/env python3
"""Check that every internal link in the documentation site resolves to a real route.

A dangling link is invisible until somebody clicks it, and the site is the public face of
the project — so this is the kind of thing that should fail a build rather than be found
by a reader. Adding the `databases` group nearly shipped a link to a concepts page that
was never written.

Routes come from two places, and both matter: the literal <Route path="..."> elements in
App.tsx, and the ones generated by mapping over commandGroups. A checker that only read
the literals would report eight false positives and get switched off.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
APP = ROOT / "docs/web/src/App.tsx"
DATA = ROOT / "docs/web/src/data"
PAGES = ROOT / "docs/web/src/pages"


def routes() -> set[str]:
    app = APP.read_text()
    found = {"/"}
    for path in re.findall(r'<Route\s+path="([^"]+)"', app):
        found.add("/" + path.lstrip("/"))

    # The command-group pages are generated: App.tsx maps over commandGroups and uses each
    # group's own `path`. Missing this is what made the first version of this script wrong.
    if "commandGroups.map" in app:
        for f in sorted(DATA.glob("commands/*.ts")):
            for p in re.findall(r"^\s*path:\s*'([^']+)'", f.read_text(), re.M):
                found.add(p)
    return found


def links() -> list[tuple[str, str]]:
    out = []
    for directory in (DATA, PAGES):
        for f in sorted(directory.rglob("*.ts")) + sorted(directory.rglob("*.tsx")):
            body = f.read_text()
            for m in re.findall(r"to:\s*'([^']+)'", body):
                out.append((m, str(f.relative_to(ROOT))))
            # <Link to="/…"> in a page, which is the other way a link is written.
            for m in re.findall(r'<Link\s+to="([^"]+)"', body):
                out.append((m, str(f.relative_to(ROOT))))
    return out


def main() -> int:
    known = routes()
    dangling = []
    checked = 0
    for target, where in links():
        if target.startswith(("http://", "https://", "mailto:", "#")):
            continue
        checked += 1
        # An #anchor is not a route; the page it hangs off is what has to exist.
        base = target.split("#")[0].rstrip("/") or "/"
        if base not in known:
            dangling.append((target, where))

    print(f"{checked} internal link(s) checked against {len(known)} route(s)")
    if not dangling:
        print("ok: every internal link resolves")
        return 0
    print("\n✗ these links point at routes that do not exist:\n", file=sys.stderr)
    for target, where in sorted(set(dangling)):
        print(f"  {target}\n      in {where}", file=sys.stderr)
    print(
        "\nEither add the route in docs/web/src/App.tsx, or correct the link.",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
